/larvol/thickness 2.0
/larvol/output output_5GeV
/larvol/write_voxel_tuple true
/larvol/write_target_tuple true
/larvol/write_histograms true

# Initialize kernel.
/run/initialize

# Set the verbosity.
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Set the number of events to be generated.
/control/alias NEvents 100000

# /gun/energy 10 GeV

# Start the run.
/run/beamOn {NEvents}