/larvol/thickness 2.0
/larvol/output output_5GeV_tuple

# Initialize kernel.
/run/initialize

/larvol/write_voxel_tuple true
/larvol/write_target_tuple true
/larvol/write_histograms true

# Set the verbosity.
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Set the number of events to be generated.
/control/alias NEvents 1000

# /gun/energy 10 GeV

# Start the run.
/run/beamOn {NEvents}